name: Make docker image

on: 
  push:
    branches:
      - main

jobs:
  ci:
    name: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: admiralissimus/diplom2:latest, admiralissimus/diplom2:0.${{ github.run_number }}.0

      - name: Checkout k8s infrastructure
        uses: actions/checkout@v3
        with:
          repository: Admiralissimus/IBA-DevOps-Practicum-Diplom2
          path: k8s

      - name: setup-yq
        # You may pin to the exact commit or the version.
        # uses: chrisdickinson/setup-yq@69aa9efdf7a9240129b103a65373c05cbc375679
        uses: chrisdickinson/setup-yq@v1.0.0
  

      - name: Change deployment.yaml in k8s repo
        run: |
          yq eval '.spec.template.spec.containers[0].image = "admiralissimus/diplom2:0.${{ github.run_number }}.0"' -i ./k8s/dev/deployment.yaml
          #sed -i 's|image: admiralissimus/diplom2:.*|image: admiralissimus/diplom2:0.${{ github.run_number }}.0|' ./k8s/dev/deployment.yaml
          cat ./k8s/dev/deployment.yaml

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: './k8s/dev/deployment.yaml'
          destination_repo: 'Admiralissimus/IBA-DevOps-Practicum-Diplom2'
          destination_folder: 'dev'
          user_email: 'actions@github.com'
          user_name: 'GitHub Actions'
          commit_message: 'Changed image version in deployment.yml to 0.${{ github.run_number }}.0'
